import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "../components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
        appearance={{
          elements: {
            signInButtonPrimary: {
              color: 'white',
              backgroundColor: '#000000',
              borderColor: '#ffffff',
              borderWidth: '1px',
              borderRadius: '8px',
              padding: '8px 16px',
              fontSize: '14px',
              fontWeight: '500'
            },
            signUpButtonPrimary: {
              color: 'white',
              backgroundColor: '#000000',
              borderColor: '#ffffff',
              borderWidth: '1px',
              borderRadius: '8px',
              padding: '8px 16px',
              fontSize: '14px',
              fontWeight: '500'
            }
          }
        }}
      >
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <NavBar />

          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}

export default RootLayout;
